✨ add button accordion
notice-project/notice pull request #16
Opened 2023-12-29 15:12 UTC by yrlin411

## 📝 Description

- added the ui components Button and Accordion
- created bookshelf basic features

## ✏️ Additional Information

2023-12-29 15:18 UTC, yrlin411 commented on src/lib/components/ui/accordion/accordion-trigger.svelte
> +  // type $$Events = AccordionPrimitive.TriggerEvents;
linter error: unused type

2023-12-29 15:18 UTC, yrlin411 commented on src/lib/components/ui/button/button.svelte
> +  // type $$Events = Events;
linter error: unused type

2023-12-30 05:44 UTC, alan910127 requested changes

2023-12-30 05:44 UTC, alan910127 commented on src/routes/bookshelf/+page.svelte
> +      on:click={addBook}
```suggestion
      onclick={addBook}
```

2023-12-30 08:06 UTC, alan910127 approved these changes

2023-12-30 08:08 UTC, merged